### ISSUE TITLE
USER STORY: Input best times and favorite track

### ISSUE THREAD

**Issue by BjornRodin** [BjornRodin/my-first-agile-project#2]
As a **user** i can **input my best times and favorite track** so that **i can follow my progress and remember which tracks i like the best**

# Acceptance Criteria
- Acceptance Criteria 1: be able to make a personal comment for future reference
- Acceptance Criteria 2: rate the tracks from 1-5 stars

# Tasks
- [ ] Make a comment section for each poll
- [ ] Create rating section with stars
- [ ] Test the functionality
