### ISSUE TITLE
USER STORY: Administrators view

### ISSUE THREAD

**Issue by BjornRodin** [BjornRodin/my-first-agile-project#3]
As a **administrator** i can **review previous polls and make new ones** so that **i can keep records of the polls and the voting details**

# Acceptance Criteria
- Acceptance Criteria 1: make more polls
- Acceptance Criteria 2: review old polls for information
- Acceptance Criteria 3: keep records of the votes

# Tasks
- [ ] Create a poll creator
- [ ] Collect previous polls and keep their records
- [ ] Test the functionality
